Repository 2024-Summer-Techeer-BootCamp-Team-E/frontend, pull requests merged in 2024-07, with the labels that each got.

#7 Design/#5 매인 페이지 1 퍼블리싱
  src/assets/images/Like.png
  src/assets/images/Main.png
  src/assets/images/Search.png
  src/components/Main/Header.tsx
  src/pages/MainPage.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
Labels: 🎨Design

#9 Design/#6 검색 결과 퍼블리싱
  src/App.tsx
  src/assets/images/Glass.png
  src/assets/images/Like.png
  src/assets/images/Liked.png
  src/assets/images/Me.png
  src/assets/images/SearchTest1.png
  src/components/SearchRes/ALiProducts.tsx
  src/pages/SearchResPage.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
Labels: 🎨Design

#11 [Design/#10] 공용 컴포넌트 퍼블리싱, 바뀐 디자인 퍼블리싱
  src/assets/images/Me.png
  src/components/Footer.tsx
  src/components/SearchRes/ALiProducts.tsx
  src/pages/SearchResPage.tsx
  tailwind.config.js
Labels: 🎨Design

#13 [Design/#8] 메인 온보딩 페이지 퍼블리싱
  src/assets/images/Arrow.gif
  src/assets/images/Click.gif
  src/assets/images/Copy.png
  src/assets/images/Feat.png
  src/assets/images/Logo.png
  src/assets/images/LookUp.gif
  src/assets/images/LowPrice.png
  src/assets/images/Original.png
  src/assets/images/Pay.png
  src/assets/images/PayCheck.png
  src/components/Main/Header.tsx
  src/index.css
  src/pages/MainPage.tsx
  tailwind.config.js
Labels: 🎨Design

#15 [Design/#12] 좋아요 페이지 퍼블리싱
  package.json
  src/App.tsx
  src/assets/images/Del.png
  src/components/Liked/CategoryBtn.tsx
  src/components/Liked/LikedProduct.tsx
  src/components/Liked/LineChart.tsx
  src/fonts/GmarketSansTTFMedium.ttf
  src/index.css
  src/pages/LikedPage.tsx
  src/pages/SearchResPage.tsx
  yarn.lock
Labels: 🎨Design

#17 [Design/#16] 좋아요, 검색 결과 페이지 디자인 개선
  src/components/HamburgerMenu.tsx
  src/components/SearchRes/OriginBtn.tsx
  src/pages/LikedPage.tsx
  src/pages/SearchResPage.tsx
  vite.config.ts
Labels: 🎨Design

#19 [Feat/#18] Framer-motion 메인 페이지 적용, 예시 데이터 수정
  package.json
  src/assets/images/SearchTest1.png
  src/assets/images/SearchTest2.jpg
  src/components/Liked/DoughnutChat.tsx
  src/components/Liked/LikedProduct.tsx
  src/components/Main/Header.tsx
  src/components/Main/MainSection1.tsx
  src/components/Main/MainSection2.tsx
  src/components/SearchRes/ALiProducts.tsx
  src/components/User/LoginModal.tsx
  src/components/User/SignupModal.tsx
  src/pages/LikedPage.tsx
  src/pages/SearchResPage.tsx
  yarn.lock
Labels: 🎨Design, ✨Feat

#21 design: 메인페이지 퍼블리싱
  src/components/Footer.tsx
  src/components/Main/Header.tsx
  src/components/Main/MainSection1.tsx
  src/components/Main/MainSection2.tsx
  src/components/Main/MainSection3.tsx
Labels: 🎨Design, ✨Feat

#28 [Feat/#25] 좋아요페이지 반응형 구현
  src/components/Liked/CategoryBtn.tsx
  src/components/Liked/DoughnutChat.tsx
  src/components/Liked/LikedProduct.tsx
  src/pages/LikedPage.tsx
  src/pages/SearchResPage.tsx
Labels: 🎨Design, ✨Feat

#31 [Feat/#29] 좋아요 api 기능 구현
  package.json
  src/components/Liked/LikedProduct.tsx
  src/pages/LikedPage.tsx
  src/pages/SearchResPage.tsx
  src/store/useLikeP.ts
  yarn.lock
Labels: ✨Feat

#33 [Feat/#32] delete 로직, 버튼 수정
  src/components/Liked/LikedProduct.tsx
  src/pages/LikedPage.tsx
Labels: ✨Feat

#41 [Feat/#40] msw로 url 정보 추출 api 기능 구현
  package.json
  public/mockServiceWorker.js
  src/components/Liked/LikedProduct.tsx
  src/components/Main/MainSection1.tsx
  src/components/User/LoginModal.tsx
  src/components/User/SignupModal.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/LikedPage.tsx
  vite.config.ts
  yarn.lock
Labels: ✨Feat

#44 chore: 도커 세팅 완료
  dockerfile
  src/App.tsx
Labels: 📚Chore

#45 [Feat/#42] url 정보 추출 api 기능 구현
  index.html
  src/assets/images/fav.ico
  src/components/Main/MainSection1.tsx
  src/components/SearchRes/OriginBtn.tsx
  src/main.tsx
  src/pages/SearchResPage.tsx
Labels: ✨Feat

#47 [Feat/#46] msw로 키워드 추출 api, 알리 api 연동 완료
  src/components/SearchRes/ALiProducts.tsx
  src/components/SearchRes/OriginBtn.tsx
  src/main.tsx
  src/mocks/handlers.ts
  src/pages/SearchResPage.tsx
Labels: ✨Feat

#49 [Feat/#37] 좋아요 페이지 무한 스크롤 기능 구현 및 메뉴 한글 화 및 로그아웃 기능 구현
  package.json
  src/components/Liked/LikedProduct.tsx
  src/components/Main/Header.tsx
  src/pages/LikedPage.tsx
  src/pages/SearchResPage.tsx
  yarn.lock
Labels: ✨Feat

#51 [Feat/#50] likedpage 로그인 기능 구현 및 비로그인 likpdage 접근 차단
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/components/Main/Header.tsx
  src/components/User/LoginModal.tsx
  src/components/User/SignupModal.tsx
  src/components/User/axiosInstance.ts
  src/pages/LikedPage.tsx
  src/pages/SearchResPage.tsx
  yarn.lock
Labels: ✨Feat

#52 [Feat/#48] 검색결과페이지 무한스크롤
  src/components/Liked/LikedProduct.tsx
  src/pages/LikedPage.tsx
  src/pages/SearchResPage.tsx
Labels: ✨Feat

#54 [feat/#53] react-query로 좋아요 기능 구현
  src/components/Liked/LikedProduct.tsx
  src/components/SearchRes/ALiProducts.tsx
  yarn.lock
Labels: ✨Feat

#56 [Design/#55] 검색결과페이지 스켈레톤ui 추가
  package.json
  src/components/Main/MainSection1.tsx
  src/components/Main/MainSection2.tsx
  src/components/SearchRes/ALiProducts.tsx
  src/components/SearchRes/SkeletonUI1.tsx
  src/components/User/LoginModal.tsx
  src/components/User/SignupModal.tsx
  src/main.tsx
  src/mocks/handlers.ts
  src/pages/SearchResPage.tsx
  tailwind.config.js
  vite.config.ts
  yarn.lock
Labels: 🎨Design, ✨Feat

#60 [Feat/#57] 카테고리 API 연동
  src/App.tsx
  src/components/Footer.tsx
  src/components/Liked/CategoryBtn.tsx
  src/components/Liked/LikedProduct.tsx
  src/components/ScrollToTop.tsx
  src/components/SearchRes/ALiProducts.tsx
  src/components/User/LoginModal.tsx
  src/components/User/SignupModal.tsx
  src/components/User/axiosInstance.ts
  src/pages/LikedPage.tsx
  src/pages/MainPage.tsx
  tailwind.config.js
Labels: ✨Feat

#62 [Feat/#61] 소비 효율 퍼센트 기능 구현 및 커서포인터 구현
  src/components/Liked/DoughnutChat.tsx
  src/components/SearchRes/ALiProducts.tsx
  src/components/SearchRes/OriginBtn.tsx
  src/pages/LikedPage.tsx
  src/pages/SearchResPage.tsx
Labels: ✨Feat

#67 [Dugfix] rollup 빌드 오류 수정
  package.json
Labels: ❤️‍🔥BugFix

#68 [Feat/#65] URL 검색창, 상품 검색창
  src/components/Footer.tsx
  src/components/Main/MainSection1.tsx
  src/hooks/URLSearch.tsx
  src/pages/LikedPage.tsx
  src/pages/SearchResPage.tsx
Labels: ✨Feat

#69 [Feat/#58] 메뉴버튼 컴포넌트화, 화면 비율 조절, 카테고리 명 업데이트 등 구현
  src/components/Footer.tsx
  src/components/Liked/LikedProduct.tsx
  src/components/Main/Header.tsx
  src/components/Main/MainSection1.tsx
  src/components/Main/MainSection2.tsx
  src/components/MenuBtn.tsx
  src/components/ScrollToTop.tsx
  src/components/User/LoginModal.tsx
  src/pages/LikedPage.tsx
  src/pages/SearchResPage.tsx
Labels: ❤️‍🔥BugFix, 🎨Design, ✨Feat

#73 [refactor/#70] 코드 컴포넌트화
  src/components/LikedPageComponents/Category.tsx
  src/components/LikedPageComponents/DoughnutChartSection.tsx
  src/components/LikedPageComponents/LikedHeader.tsx
  src/components/LikedPageComponents/ProductList.tsx
  src/components/LikedPageComponents/SearchBar.tsx
  src/components/Main/MainSection1.tsx
  src/pages/LikedPage.tsx
Labels: 🔨Refactor

#75 [Feat/#74] 카테고리 수정
  src/components/Liked/Category.tsx
  src/components/Liked/DoughnutChartSection.tsx
  src/components/Liked/LikedHeader.tsx
  src/components/Liked/LikedProduct.tsx
  src/components/Liked/ProductList.tsx
  src/components/Liked/SearchBar.tsx
  src/components/SearchRes/ALiProducts.tsx
  src/pages/LikedPage.tsx
  src/pages/SearchResPage.tsx
Labels: ✨Feat
